# Enviados de la Sombra
:toc:
:toclevels: 3
:toc-title: Contenido

Campaña narrativa de Rolemaster ambientada en la Tierra Media.

El protagonista es Shaktur, un numenoréano negro de las tierras al sur de Umbar al que le es encomendada una misión en Minas Morgul.

## Actores

- Shaktur: numenoréano negro protagonista principal. Tras la muerte de su padre recibe un mensaje de Azgar para viajar hacia Minas Morgul para participar en una misión.
- Azgar: numenoréano negro noble con conexiones políticas en Mordor. Es el valedor de Shaktur y quién le ha recomendado para la misión aún sin conocerle directamente ya que es el hijo de un amigo suyo.
- Xught: comisario orco al mando de la expedición inicial.
- Grukk: explorador orco de Minas Morgul conocedor de los bosques de Ithilien.
- Agannâlu: numenoréano negro que lidera la misión de rescate de Grukk.
- Azak: capitán de Gondor caído durante el ataque de la primera misión.

## Capítulo 1: La Partida

_Yo, Sauron, Señor de Barad-dûr, Hacedor del Anillo y Dueño del Destino de la Tierra Media, hago llegar estas palabras a mi siervo fiel, numenóreano negro, portador de mi voz y ejecutor de mi designio. +
Escucha sin error, memoriza sin duda, y cumple sin demora. +
Tu misión es avanzar en secreto hacia el gran río Anduin y asegurar su ladera oriental, desde los pasos septentrionales hasta donde el bosque y la niebla se espesan. +
Esta franja será la vena por la que fluirá mi influencia cuando llegue la hora abierta de la guerra. +
No levantarás estandartes.
No provocarás batallas innecesarias.
El miedo debe preceder a la vista. +
Establece posiciones ocultas en colinas, gargantas y pasos elevados.
Vigila los movimientos de hombres del sur y jinetes errantes, Informa de toda patrulla.
Usa aliados menores, sombras y rumores para debilitar la voluntad del enemigo antes del choque._

_El Este del Anduin debe parecer tranquilo a medida que nos apoderamos de él.
Contactarás, en mi nombre, con los dominios de Moria y la Ciudad de los Trasgos y hazles saber que una nueva guerra se cierne en el horizonte. Saruman ha cedido a la voluntad del anillo pero mi influencia aún es débil. Extrae alguna información de sus planes ya que desconfío de sus intenciones.
Coordina escaramuzas, rutas de paso y refugios. Que se preparen armas, víveres y carne para la guerra venidera.
Evita atraer la atención de los vigilantes del oeste.
Los bosques escuchan.
Los ríos recuerdan.
Si caes, que sea sin nombre.
Si triunfas, tu recompensa será vivir bajo mi sombra cuando el mundo sea rehecho.
Así lo ordeno. Así será. +
La Sombra se alarga. +
El Anillo llama. +
Los caminos conducen a mí._

=== Cuaderno de Viaje de Xught, Comisario de Gotmoth, Lugarteniente de Minas Morgul

_Los siguientes informes son enviados a la ciudadela usando Crebains mensajeros._

*29 de Enero del 2942*

La expedición parte de Minas Morgul con Shaktur al mando, un numemoráneo negro que ha llegado a la ciudadela hace tres noches. Avanzaremos moviéndonos por la noche escondidos a través de los bosques de Ithilien hacía el delta del Anduin donde contactaremos con un puesto de guardia que ha sido informado de nuestra llegada.

*30 de Enero de 2942*

Avanzamos 10 millas sin ningún imprevisto. Llevamos provisiones para 10 días. Nuestro explorador ha informado de un grupo de exploradores vigilando una de las rutas. Mañana se evaluará la amenaza para atacarlos mientras duermen o seguiremos avanzando sin ser detectados.

*31 de Enero de 2943*

Grukk, nuestro explorador ha informado que los exploradores están escondidos en las ruinas de una loma. Se trata de un grupo de seis humanos. Shaktur ha decidido asaltar su campamento mientras hacen guardia de noche y ha partido hace una hora.
Espero con los orcos de guardia preparando el campamento para pasar el día de mañana ocultos en la espesura del bosque.

...

Shaktur ha regresado sólo informando de que los gondorianos a los que iban a asaltar les han tendido una emboscada sin haber especificado su número de forma precisa. Su vestimenta está desgarrada y ensangrentada. Alguna cosa no cuadra ya que mucha sangre que le cubría no tenía el color carmesí de la sangre humana sino el color pardo espeso de nuestra sangre. Nos esconderemos esta noche y partiremos mañana de regreso a la ciudadela para establecer otra partida de exploración. Desconfío de Shaktur al que solo conozco de hace tres días ya que Grukk siempre ha resultado un buen rastreador durante todos los años que he trabajado con él y conocía este bosque como la palma de su mano.

...

=== Grukk

Grukk es el explorador de la expedición. En el segundo día de la expedición localiza a un pequeño campamento de exploradores y Shaktur decide preparar una emboscada nocturna que debería haber sido una operación sencilla pero por el exceso de confianza de Shaktur que realiza un ataque directo sin ninguna coordinación acaba resultando desastroso.

Después del ataque donde un explorador escapa y el resto de orcos han muerto o están agonizando y moribundos, Shaktur amenaza a Grukk para que no delate la incompetencia de este y al tener una negativa lo ataca y hiere gravemente en el brazo.

Herido gravemente y desarmado Grukk consigue huir aprovechando la oscuridad de la noche mientras Shaktur es incapaz de seguir su rastro.

Escondido entre unas rocas mientras trata de parar la hemorragia de su brazo permanece atento a los sonidos de la noche hasta estar seguro de que Shaktur ha perdido su rastro.

Armado sólamente con un cuchillo y temblando de frío se mueve cautelosamente para buscar un lugar seguro donde terminar la noche y descansar mientras el frío Sol de invierno aún es capaz de afectar a sus sentidos.

[Tirada de supervivencia-modor: 29 + 2 (env skill): fallo gordo]:

No logra ningún lugar adecuado para el descanso y se queda escondido entre unas rocas.

[Primera activación de tabla de encuentros: 44: Mamiferos: jabalies/osos/alces, tirada de tipo: 9: alces. Arquetipo defensivo. Tirada de interacción 41, nada relevante]

El pobre orco sin dormir se debatirá sobre el sinsentido de la vida y aunque su reacción sería la de regresar sabe que si en algún momento es "mi palabra contra la suya" no hay organismos de jurisprudencia que le garanticen que la versión de un Numemoraneo de la confianza del regimen valga mucho mas que la suya

Los pensamientos de Grukk se van diluyendo a lo largo de la noche mientras piensa en todo aquello que ama y recuerda su infancia y adolescencia

Y con esos pensamientos en la cabeza y exausto por las heridas y la inseguridad se queda parcialmente dormido apoyado

A medida que su temperatura corporal baja y aumenta la sed trata de olvidarse de las particularidades de su lamentable situación y tratará de vivir lo que le quede de vida conforme a sus principios mas elementales, aun siendo estos dominados por la volundad del anillo.

== Capítulo 2: El Juicio

Shaktur regresó a Minas Morgul con Xught y dos porteadores orcos.

No entró como vencedor. Entró de noche, cuatro días después de su partida. Con manchas de sangre seca en la ropa, los labios resecos y el aspecto agotado de quien ha recorrido varias millas sin apenas descanso durante los meses frios de Ithilien.

Antes de que se abriese la puerta de servicio de la ciudadela la espera fue tensa. Intercambiaba duras miradas con Xught mientras este la esquivaba. Apenas habían hablado unas pocas frases durante los últimos dos días donde habían estado regresando tras sus pasos sobre la nieve y el barro.

Los informes de Xught habían llegado la noche anterior bajo las alas de los crebain mensajeros. El comisario había escrito poco, pero suficiente. La partida había salido mal. Casi todos los orcos habían muerto o habían desaparecido. La versión de Shaktur olía a miedo y a mentira.

Ni dos noches habían bastado para que todo se pudriera.

Tras entrar en la ciudadela Shaktur fue a visitar las estancias de Azgar, su protector en Minas Morgul. Azgar lo recibió en una estancia baja de la ciudadela tras abrirle la puerta con aspecto escéptico. Era un numenóreano negro que había servicio largo tiempo en Mordor, respetado por sus mandos y con buenas conexiones en el tejido de las tierras oscuras durante una época en la que la reconstrucción de Barad-dûr había convertido la región en un crisol de facciones con intereses encontrados deseosos de ganarse el favor de los capitanes.

Las palabras ya no servían. El asesinato de los orcos con sus manos no constituía ningún problema, pero el desempeño de la misión era sido tan decepcionante que había llegado a demasiados oídos.

En Minas Morgul había leyes y la jurisprudencia la dictaba el acero. Había fallado en la misión pero tenía una salida para limpiar su nombre, un juicio por combate donde la voluntad de Morgoth dictaminaría su capacidad.

Shaktur aceptó. La alternativa era una huida hacia las tierras de Umbar y la deshonra de Azgar quién había sido su valedor y quién le recomendó para la empresa.

Su rival sería Khamzar, un guerrero de Rhûn de mediana edad, fuerte, curtido en numerosas escaramuzas contra gondorianos y rohirim. Mandaba a hombres duros del este, bárbaros acostumbrados al frío, al hambre, las penalidades y la violencia de las tierras al norte de Mordor. Gothmog le tenía aprecio. Eso bastaba para hacerlo peligroso.

El combate se preparó fuera de la ciudadela, en un campamento hundido en barro en los restos de las antiguas edificaciones de los hombres, muchas ahora convertidas en cuadras para huargos y tiendas de campaña alternadas con letrinas, provisiones y los talleres de los artesanos. 

Enfrente del lugar de combate se levantó una tribuna improvisada de madera. Gothmog presidiría en el centro del palco flanqueado por sus principales capitanes.

Allí Shaktur demostraría su valor o sus días terminarían en aquél barro.

Khamzar formó con sus mejores hombres. En el centro estaba él, escoltado por tres guerreros de confianza. A su alrededor, sus orientales esperaban con lanzas, espadas, arcos y escudos desgastados.

Shaktur reunió a las unidades que Azgar se había encargado de buscar. Tres numenoraneos negros junto con puñado de orcos menores. Pocos. Sucios. Nerviosos.

Sonó el cuerno.

Khamzar avanzó despacio, midiendo el terreno mientras esperaba que los arqueros tomaban posiciones sobre las alturas en las ruinas cercanas y se hizo fuerte tras un conjunto de barriles y cajas de provisiones.

Shaktur no esperó. Cargó directo al centro.

Fue una decisión estúpida. También fue valiente. Cruzó el barro con los suyos detrás, sin buscar flancos ni ventaja. Fue contra Khamzar y sus tres mejores guerreros como si la única forma de limpiar su nombre fuera romperse los dientes contra la parte más dura del enemigo.

Llevado por su propia rabia llego hasta los guardaespaldas de Khamzar que se defendían usando picas y escudos de los ataques de Shaktur. Flanqueado por varios orcos se escuchaban los gritos mientras los cuerpos chocaban y caían al barro.

Unos minutos después volvió a sonar un cuerno. Entonces Gothmog alzó la mano y sin parar a decir una sola palabra giró sobre sus pies y desaparecio seguido de su guarda pretoriana.

Shaktur quedó en pie.

Magullado, jadeando, cubierto de sangre y barro. Miró a Khamzar desafiantemente mientras recuperaba la respiración. A su lado varios orcos se desangraban en el barro cerca de otros agonizantes o inconscientes.

Mientras un grupo de orcos corría a auxiliar a los heridos Shaktur busco a Azgar entre las figuras de la tribuna. Al dar con el vio como este sonreía animado y le dedicó un gesto afectado de aprobación.

== Capítulo 3: La Captura de Grukk

El día siguiente al combate Shaktur despertó en los barracones de una torre menor de Minas Morgul rodeado de orcos heridos tendido en un camastro con sábanas raídas del que por los numerosos agujeros sobresalía paja malolienta.

Tenía el torso ceñido por vendas, el labio partido y una hinchazón en la mandíbula que le obligaba a mover la boca con cuidado.

Azgar le despertó meneándole con el pie.

-No tienes muy buen aspecto, aunque la voluntad parece que quiere que sigas vivo- dijo a medida que Shaktur se desperezaba.

Shaktur se tocó el mentón y movió la barbilla despacio.

-Tienes más cojones que cabeza. Eso sin duda.

Azgar se acercó a la mesa donde estaban las pertenencias de Shaktur, tomó una botella de licor y arrancó el corcho con sus dientes torcidos. Bebió un trago largo antes de mirar de nuevo a Shaktur.

-Han encontrado a Grukk.

Shaktur no respondió.

-Un grupo de exploradores de Ithilien dio con él a varias millas del lugar del ataque. Medio muerto, helado y con el brazo hecho una ruina. Un confidente dentro de la guardia ha enviado aviso a la ciudadela. Lo han llevado a un puesto avanzado.

Azgar se limpió con la manga los labios mojados de licor.

-Lo estarán interrogando -continuó Azgar-. Y cuando los hombres de Gondor empiezan a preguntar, terminan oyendo lo que quieren oír. Aunque Grukk solo les diga que el agua moja, esa información no debe llegar a Osgiliath. Nadie sabe lo que esas orejas de orco han escuchado, pero a nadie le interesa que nuestros planes se vayan haciendo conocidos al otro lado del Anduin.

Shaktur se incorporó un poco sobre el camastro.

-¿Me estás pidiendo ayuda?

Azgar se pudo serio.

-Que Morgoth me acoja si alguna vez necesito pedirte ayuda. No, toda esta, mierda, -hizo una pausa-, todo este desastre ya no tiene que ver directamente conmigo. Ahora es Agannâlu quién está al mando. Este tipo no es tan cosiderado como yo y como proviene de tu error me ha pedido que te diga que te da la posibilidad del desagravio participando en la misión de rescate, o de caza. Es más fácil que las bocas estén cerradas debajo del suelo que encima de él.

Shaktur apartó la manta con lentitud. El dolor le subió desde las costillas hasta la nuca.

Azgar volvió a beber.

-Saldréis esta tarde desde las caballerizas de Morgul, si puedes mantenerte sobre un caballo. Os uniréis a una partida de caza orca que ha avanzado desde el sur durante la noche. Hay varias leguas hasta el puesto de los exploradores y la urgencia no admite más demora.

Shaktur cerró los ojos un instante. Necesitaba descanso, apenas había dormido unas pocas horas por el dolor la noche anterior.

-Entonces necesitaré dormir alguna hora más.

-Duerme. Mandaré que te despierten con tiempo para comer algo y remojarte las pelotas antes de ensillar. Procura matar más gondorianos que orcos esta vez- rio Azgar mientras se secaba los labios con la manga.

Azgar dejó sobre la mesa un pequeño vial con un líquido oscuro.

-Ya me fallaste la primera vez. Si me fallas una segunda no quiero verte otra vez cruzando el portón de la ciudadela.

La amenaza quedó flotando en la habitación.

Luego Azgar añadió, con una mueca torcida:

-Si vuelves con Grukk o con su lengua en una bolsa, quizá te deje celebrar la noche con una de mis chicas.

Sus pasos se alejaron por la escalera.

Shaktur se incorporó lo justo para beber un poco de agua. Miró el vial oscuro sobre la mesa y lo lanzó de un manotazo al suelo.

Después volvió a dejarse caer sobre aquél montón de paja humedecida por el sudor que se le pegaba a la piel.

...

Unas horas más tarde un pequeño orco no más grande que un mediano le despertó con su voz áspera y gutural.

-Amigo, recoja sus cosas, debes acompañarme.

Abriendo un ojo vio a cuatro orcos detrás que ya estaban cogiendo su armadura y pertenencias y se disponían a cargar con ellas.

Muerto de cansacio volvió a dejar caer su cabeza sobre el camastro, darme unos minutos.

-Amo decir que no hay tiempo.

Shaktur dijo en voz alta varias palabras en una lengua que los orcos no entendían mientras dijo -de acuerdo, llevarme donde demonios sea.

A pocos minutos le condujeron a las caballerizas. Aún era media tarde y el Sol invernal brillaba sin apeñas fuerza haciendo de la ciudadela un lugar siniestro.

Al llegar dos numenoréanos hablaban entre ellos. Al ver a Shaktur, el más alto de ellos dijo maliciosamente

-Aquí está nuestro héroe y detrás, un pequeño grupo de orcos se dejó llevar por alguna carcajada. Shaktur andaba aún lastimosamente y sus ropajes se veían ahora como harapos.

...

Tras recibirlo, Agannâlu no es muy amistoso. Le dice que elija un caballo mientras hace un chiste de mal gusto sobre que es para montarlo, no para tener relaciones. En las caballerizas apenas hay unos caballos con buen aspecto.

Shaktur escoge uno, Agannâlu le dice que ese no. Vuelve a repetirlo, Agannâlu le dice que tampoco. Poco a poco se crea un clima de tensión. Al final sólo queda una joven yegua de color gris que parece que no podrá soportar su propio peso.

Cuando Skaktur se dispone a ensillar y cargar la armadura le dicen que no hará falta, que Morgoth está de su parte e interferirá por el y que las armaduras hacen demasiado ruido.

Puedes coger algún trapo en la armería si no quieres pasar frio bromeó Agannâlu.

NOTE: En esta misión Shaktur sólo irá con una armadura de cuero ligero

-Te explicaré la misión, llegamos, nos unimos a la partida de caza de los orcos, matamos a todos y volvemos. ¿Alguna pregunta?

Shaktur vio que los dos numenoreaneos llevaban armaduras de malla y comprendió que iba a ser usado de carne de cañon.

Tras pasar por la armería donde Shaktur cogió un chaleco de cuero que le quedaba algo pequeño volvió con Agannâlu.

-El explorador nos está esperando-. Los tres caballos seguidos de dos huargos partieron al galope atravesando ruidosamente el foso de la ciudadela mientras las herraduras metálicas de los caballos explotaban contra la piedra del suelo.

Estuvieron varias horas galopando hasta llegar al lugar acordado.

Allí estaba una pareja de exploradores orcos apostados entre una formación de rocas.

-¿Y el resto?- preguntó Agannâlu a uno de los exploradores.

-Deberían haber llegado hace horas, no tenemos aún noticias de ellos

Agannâlu miró los últimos rayos de Sol previos al anochecer. -Por qué en esta vida dios quiere que solo me vea rodeado de inutiles. Atar a los caballos.

Shaktur desmontó y se sentó sobre una roca. La travesía a caballo había hecho que le doliera cada uno de los huesos del cuerpo. Se llevó la mano a palparse las cosillas por debajo del peto de cuero, no parecía rota pero dolía como si lo estuviera.

A lo lejos Agannâlu y sus dos lugartenientes hablaban con los exploradores. Se les veía alterados. La noche era gélida y sin un fuego para calentarse las manos y los pies se le entumecían.

Al cabo de media hora Agannâlu se acercó a Shaktur. -No podemos esperar más tiempo. Debemos hacerlo ahora.

Era una noche de luna llena y la cara de Agannâlu brillaba pálidamente. El plan no marchaba bien.

-¿Sabemos cuantos son? preguntó con voz baja Shaktur.

-Pocos. El puesto de guardia está a dos millas, deberemos partir ya- dijo friamente.

-Hay un gondoriano que no deberemos matar, lleva un pañuelo amarillo en el cuello. Es nuestro confidente. Del resto, -sonrio-, no necesitamos prisioneros, si ves algún mandingo que te guste te lo puedes quedar- rio.

Mientras se preparaban para la batalla Shaktur estuvo inspeccionando con la yema de los dedos el filo de su espada. Necesitaba un buen afilado pensó.

Y el grupo formado por los cuatro numenoreanos, el guía orxo y los dos exploradores comenzaron su caminata sigilosa hacia el cuartel.

-Shaktur, tu te acercarás para acabar con los guardias. Nosotros cubriremos los flancos. Atrancaremos la puerta desde fuera y prenderemos fuego, así conocerás como grita un gondoriano a la parrilla.


